### ISSUE TITLE
NotNullViolation while trying to create a new inspection in `fertiscan`

### ISSUE THREAD

**Issue by k-allagbe** [ai-cfia/ailab-datastore#146]
Using the deployed fertiscan, and analyzing this image:
![image](https://github.com/user-attachments/assets/c5c5b9de-2b38-46e1-846d-e929a57b064d)

The label analysis data obtained from the pipeline:
```json
{
  "company_name": "Scotts Canada Ltd./Ltée",
  "company_address": "2000 Argentia Road Plaza 5, Suite 101, Mississauga, Ontario LSN 2R7",
  "company_website": null,
  "company_phone_number": null,
  "manufacturer_name": null,
  "manufacturer_address": null,
  "manufacturer_website": null,
  "manufacturer_phone_number": null,
  "fertiliser_name": "Scotts Turf Builder LAWN FOOD",
  "registration_number": null,
  "lot_number": null,
  "weight": [],
  "density": null,
  "volume": null,
  "npk": "30-0-3",
  "guaranteed_analysis": [{ "nutrient": "IRON", "value": "20", "unit": null }],
  "warranty": null,
  "cautions_en": [],
  "instructions_en": [
    "Regular feeding's provide the nutrients for a healthy lawn to develop a deep root system capable of crowding out weeds and withstanding the stresses of beat; drought and insect infestations."
  ],
  "micronutrients_en": [],
  "ingredients_en": [],
  "specifications_en": [],
  "first_aid_en": [],
  "cautions_fr": [],
  "instructions_fr": [
    "Les fertilisations régulières procurent les nutriments permettant à une pelouse en santé de développer un système racinaire profond, capable de surclasser les mauvaises herbes et de résister au stress attribuable à la chaleur, à la sécheresse et aux infestations d'insectes."
  ],
  "micronutrients_fr": [],
  "ingredients_fr": [],
  "specifications_fr": [],
  "first_aid_fr": []
}

```

Error logs:
```
2024-09-05 13:14:57,716 - __main__ - ERROR - Error occurred: Datastore Inspection Creation Error
2024-09-05 13:14:57,717 - __main__ - ERROR - Traceback: Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/datastore/db/queries/inspection/__init__.py", line 78, in new_inspection_with_label_info
    cursor.execute(query, (user_id, picture_set_id, label_json))
  File "/usr/local/lib/python3.11/site-packages/psycopg/cursor.py", line 732, in execute
    raise ex.with_traceback(None)
psycopg.errors.NotNullViolation: null value in column "address" violates not-null constraint
DETAIL:  Failing row contains (e771ada6-7217-4b77-ae5d-6ad8bcea23d4, null, null, null, null).
CONTEXT:  SQL statement "INSERT INTO location (address)
        VALUES (
            input_json->'manufacturer'->>'address'
        )
        RETURNING id"
PL/pgSQL function new_inspection(uuid,uuid,jsonb) line 61 at SQL statement
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/datastore/fertiscan/__init__.py", line 83, in register_analysis
    analysis_db = inspection.new_inspection_with_label_info(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/datastore/db/queries/inspection/__init__.py", line 81, in new_inspection_with_label_info
    raise InspectionCreationError(e.__str__())
datastore.db.queries.inspection.InspectionCreationError: null value in column "address" violates not-null constraint
DETAIL:  Failing row contains (e771ada6-7217-4b77-ae5d-6ad8bcea23d4, null, null, null, null).
CONTEXT:  SQL statement "INSERT INTO location (address)
        VALUES (
            input_json->'manufacturer'->>'address'
        )
        RETURNING id"
PL/pgSQL function new_inspection(uuid,uuid,jsonb) line 61 at SQL statement
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/app.py", line 203, in create_inspection
    inspection = asyncio.run(
                 ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/datastore/fertiscan/__init__.py", line 88, in register_analysis
    raise Exception("Datastore Inspection Creation Error")
Exception: Datastore Inspection Creation Error

```

**Comment by Francois-Werbrouck** [comment]
We need the json, not the image to test out this issue.

**Comment by k-allagbe** [comment]
> We need the json, not the image to test out this issue.

Done.

**Comment by k-allagbe** [comment]
The issue persists.

input json:
```json
{
    "company_name": null,
    "company_address": null,
    "company_website": "lesgranulaines.com",
    "company_phone_number": null,
    "manufacturer_name": null,
    "manufacturer_address": null,
    "manufacturer_website": null,
    "manufacturer_phone_number": null,
    "fertiliser_name": "ALL-PURPOSE NATURAL FERTILISER",
    "registration_number": null,
    "lot_number": "L-1",
    "weight": [],
    "density": null,
    "volume": null,
    "npk": "10-0-4",
    "guaranteed_analysis": [
      { "nutrient": "Total nitrogen (N)", "value": 10, "unit": "%" },
      { "nutrient": "Soluble potash (K2O)", "value": 0.4, "unit": "%" },
      { "nutrient": "Organic matter", "value": 61.5, "unit": "%" }
    ],
    "warranty": null,
    "cautions_en": ["Wash your hands after use.", "Keep away from children."],
    "instructions_en": [
      "Garden: incorporate 150 to 200 grams of Granu-Laines per m2 into first top 10 cm of soil before seeding.",
      "Tomato: incorporate 150 grams underneath each plant.",
      "Cucumber and squash: Incorporate 100 grams underneath each plant.",
      "For cultivating in pots or large containers, mix in 50 grams of Granu-Laines per 4 liters of soil.",
      "For any questions, please contact your garden center."
    ],
    "micronutrients_en": [],
    "ingredients_en": [
      { "nutrient": "Ingredients", "value": null, "unit": "100% raw sheep wool" }
    ],
    "specifications_en": [{ "humidity": 14.8, "ph": null, "solubility": null }],
    "first_aid_en": [],
    "cautions_fr": [
      "Se laver les mains apr\u00e8s chaque utilisation.",
      "Garder hors de la port\u00e9e des enfants."
    ],
    "instructions_fr": [
      "Pour votre potager, incorporer 150 \u00e0 200g de Granu-Laines par m2 de sol.",
      "Concombre et courge: incorporer 100g sous chaque plante.",
      "Tomate: incorporer 150g sous chaque plant.",
      "Pour la culture en pot ou en bac, incorporer 50g par 4 litres de terre.",
      "Et en cas de besoin, renseignez-vous \u00e0 votre centre jardin."
    ],
    "micronutrients_fr": [],
    "ingredients_fr": [
      {
        "nutrient": "Ingr\u00e9dients",
        "value": null,
        "unit": "100% laine brute de moutons"
      }
    ],
    "specifications_fr": [{ "humidity": 14.8, "ph": null, "solubility": null }],
    "first_aid_fr": []
  }
  
```


results:
```bash
Error occurred: null value in column "address" of relation "location" violates not-null constraint
DETAIL:  Failing row contains (d4a35038-f12f-4223-b5eb-75fef9ef8add, null, null, null, null).
CONTEXT:  SQL statement "INSERT INTO location (address)
        VALUES (
            address_str
        )
        RETURNING id"
PL/pgSQL function new_organization_info_located(text,text,text,text,boolean) line 22 at SQL statement
PL/pgSQL function new_inspection(uuid,uuid,jsonb) line 48 at assignment
Database connection closed.
```
